[theme]

# The preset Streamlit theme that your custom theme inherits from. One of "light" or "dark".
base = "light" 
primaryColor="#3f72af"
backgroundColor="#f9f7f7"
secondaryBackgroundColor="#dbe2ef"
textColor="#06162D"
# textColor="black"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
font = "sans serif"


# Description of what colors mean
# Primary accent color for interactive elements.
# primaryColor = "red"

# Background color for the main content area.
# backgroundColor = "rgb(240, 252, 246)"

# Background color used for the sidebar and most interactive widgets.
# secondaryBackgroundColor = "red"

# Color used for almost all text.
# textColor = "black"

